# Generated by Django 4.0.2 on 2022-03-12 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.UUIDField(db_column='Coach ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(db_column='Coach Name', max_length=10)),
                ('available_seats', models.IntegerField(db_column='Available Seats')),
            ],
        ),
        migrations.CreateModel(
            name='CoachType',
            fields=[
                ('coach_type_id', models.UUIDField(db_column='Coach Type ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coach_type', models.CharField(db_column='Coach Type', max_length=10)),
                ('coach_capacity', models.IntegerField(db_column='Coach Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.UUIDField(db_column='Station ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_name', models.CharField(db_column='Name', max_length=50)),
                ('no_of_platforms', models.IntegerField(db_column='No of platform')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.UUIDField(db_column='Train ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_no', models.CharField(db_column='Train No', max_length=5, unique=True)),
                ('train_name', models.CharField(db_column='Train Name', max_length=50)),
                ('total_ac_coach', models.IntegerField(db_column='Total AC Coach')),
                ('total_n_ac_coach', models.IntegerField(db_column='Total Non AC Coach')),
                ('total_seater', models.IntegerField(db_column='Total Seats')),
                ('dest_station', models.ForeignKey(db_column='Dest Station', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dest_staion', to='api.station')),
                ('src_station', models.ForeignKey(db_column='Source Station', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_src_station', to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(max_length=10)),
                ('coach', models.ForeignKey(db_column='Coach', on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('dest_station', models.ForeignKey(db_column='Station Booked Till', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_station_till', to='api.station')),
                ('src_station', models.ForeignKey(db_column='Station Booked From', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_station_booked', to='api.station')),
                ('train', models.ForeignKey(db_column='Train', on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_stop_no', models.IntegerField(db_column='Train Stop No')),
                ('station', models.ForeignKey(db_column='Station', on_delete=django.db.models.deletion.CASCADE, to='api.station')),
                ('train', models.ForeignKey(db_column='Train', on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField(db_column='Seat No')),
                ('coach', models.ForeignKey(db_column='Coach', on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('train', models.ForeignKey(db_column='Train', on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='SeatBookedTill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_from', models.ForeignKey(db_column='Station Booked From', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_station_booked', to='api.station')),
                ('booked_till', models.ForeignKey(db_column='Station Booked Till', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_station_till', to='api.station')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seats')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_type',
            field=models.ForeignKey(db_column='Coach Type', on_delete=django.db.models.deletion.CASCADE, to='api.coachtype'),
        ),
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(db_column='Train', on_delete=django.db.models.deletion.CASCADE, to='api.train'),
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNo', models.IntegerField(db_column='Seat No')),
                ('passengerName', models.CharField(db_column='Passenger Name', max_length=20)),
                ('ticket', models.ForeignKey(db_column='Ticket', on_delete=django.db.models.deletion.CASCADE, to='api.ticketbooking')),
            ],
        ),
    ]
